---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/uploads
  label: Uploads
  create: all
  match: "**/*"
- type: directory
  path: content/portfolio
  label: Portfolio
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - quote1-md
  - client
- type: directory
  path: content/blog
  label: Blog
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - blog1-md
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.51'
