---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/uploads
  label: Uploads
  create: none
  match: "**/*"
  exclude: _index.md
- type: directory
  path: content/portfolio
  label: Portfolio
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - new-client
  - quote1-md
  - client
- type: directory
  path: content/blog
  label: Blog
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - blog1-md
upload_dir: content/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.51
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.51
  preview_output_directory: public
  output_directory: public
version: '0.51'
